##### BANCO DE DADOS
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
#quarkus.datasource.jdbc.url=jdbc:h2:mem:default
#quarkus.datasource.jdbc.url=jdbc:h2:file:./import.sql;AUTO_SERVER=TRUE
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;INIT=RUNSCRIPT FROM 'classpath:scriptInicial.sql'
quarkus.hibernate-orm.log.sql=false

# Rest
quarkus.rest-client.executar-task-host.url=http://localhost:8080

# Reduzir o pacote do log
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n
##2026-04-19 10:32:06,731 INFO  [br.com.bbts.shopee.resources.ListarDadosClientesResource] (executor-thread-1) 
##10:35:32 INFO  [b.c.b.s.r.ListarDadosClientesResource] (executor-thread-1) Quantidade de itens retornados da Shopee: 3


#quarkus.hibernate-orm.database.generation=update
#quarkus.hibernate-orm.mysql.datasource=mysql
#quarkus.hibernate-orm.packages=br.com.bbts

## PARA FUNCIONAR O CORS, MAS NAO SEI SE VAI FUNCIONAR NO SERVIDOR SEM SER DEV.
#%dev.quarkus.http.cors.origins=/.*/
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST
quarkus.http.cors.headers=X-Custom
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true